In [20]:
import os
import pandas as pd
import humanreadable as hr

In [2]:
path = os.path.abspath(os.path.join(os.path.abspath(""), os.pardir))
nb_rates = 30
chronicle = 0
scale = "BVE"

# Different sets of features 
set_geomorph = ["Slope", "Elevation", "LC", "CW", "Area"]
set_CVHV = ["Coastal Vulnerability", "Hydrological Vulnerability"]
set_saturation= ["Satured Zone Area", "Vulnerability Sum", "Vulnerability Rate"]
set_cells = ["Number of Cells"]
all_features = set_geomorph + set_CVHV + set_saturation + set_cells

# We select the type of features we want to use for training our model
#features = set_cells

In [4]:
df_data = pd.read_csv(os.path.join(path, "data/", "Input_Data_Time_ValidMetric_Features_Rates_" + str(nb_rates) + "_Features_" + "Geomorph_CVHV_Saturation_Cells" + "_" + str(scale) + "_Comparable.csv"), sep=";")

In [5]:
df_data

,SiteNumber,Chronicle,Rate,Validation Metric,Accuracy,Time,Slope,Elevation,LC,CW,Area,Coastal Vulnerability,Hydrological Vulnerability,Satured Zone Area,Vulnerability Sum,Vulnerability Rate,Number of Cells
0,1,0,1.0,0.000000,100.000000,34367,0.017383,14.0310,1575.0,2.2527,57077000.0,1906,1033,10373,10398.720357,0.296041,35126
1,1,0,2.0,0.003879,96.120677,18464,0.017383,14.0310,1575.0,2.2527,57077000.0,1906,1033,10373,10398.720357,0.296041,35126
2,1,0,7.0,0.016209,83.791104,8508,0.017383,14.0310,1575.0,2.2527,57077000.0,1906,1033,10373,10398.720357,0.296041,35126
3,1,0,15.0,0.025983,74.017172,4975,0.017383,14.0310,1575.0,2.2527,57077000.0,1906,1033,10373,10398.720357,0.296041,35126
4,1,0,21.0,0.031977,68.023203,4560,0.017383,14.0310,1575.0,2.2527,57077000.0,1906,1033,10373,10398.720357,0.296041,35126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,30,0,2000.0,0.142734,-42.733912,354,0.009400,7.9139,1800.0,2.0684,46513000.0,841,1156,19157,19204.851462,0.393413,48816
746,30,0,2250.0,0.150898,-50.897853,273,0.009400,7.9139,1800.0,2.0684,46513000.0,841,1156,19157,19204.851462,0.393413,48816
747,30,0,3000.0,0.161572,-61.572397,177,0.009400,7.9139,1800.0,2.0684,46513000.0,841,1156,19157,19204.851462,0.393413,48816
748,30,0,3182.0,0.165746,-65.745917,188,0.009400,7.9139,1800.0,2.0684,46513000.0,841,1156,19157,19204.851462,0.393413,48816
749,30,0,3652.0,0.168162,-68.161842,134,0.009400,7.9139,1800.0,2.0684,46513000.0,841,1156,19157,19204.851462,0.393413,48816

In [41]:
df_ref_runs = df_data.loc[df_data['Rate'] == 1.0]
df_ref_runs.describe()

,SiteNumber,Chronicle,Rate,Validation Metric,Accuracy,Time,Slope,Elevation,LC,CW,Area,Coastal Vulnerability,Hydrological Vulnerability,Satured Zone Area,Vulnerability Sum,Vulnerability Rate,Number of Cells
count,25.000000,25.0,25.0,25.0,25.0,25.000000,25.000000,25.000000,25.000000,25.000000,2.500000e+01,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000
mean,16.680000,0.0,1.0,0.0,100.0,21594.560000,0.019888,18.213396,1602.000000,2.389576,3.903680e+07,1025.400000,972.000000,4189.080000,4214.650422,0.148995,24819.000000
std,8.360223,0.0,0.0,0.0,0.0,15373.603712,0.015272,13.533656,265.058956,0.550499,2.683362e+07,1447.308162,888.377407,5397.120296,5403.684044,0.113589,16164.181452
min,1.000000,0.0,1.0,0.0,100.0,1849.000000,0.000574,2.460900,1350.000000,1.557700,3.273800e+06,0.000000,15.000000,258.000000,262.213506,0.023108,3762.000000
25%,11.000000,0.0,1.0,0.0,100.0,9185.000000,0.009446,7.913900,1425.000000,2.068400,1.545200e+07,102.000000,251.000000,635.000000,645.083106,0.058985,11880.000000
50%,17.000000,0.0,1.0,0.0,100.0,16901.000000,0.017383,13.120000,1575.000000,2.252700,3.857100e+07,515.000000,931.000000,2149.000000,2157.415818,0.107054,19460.000000
75%,23.000000,0.0,1.0,0.0,100.0,35227.000000,0.023758,29.454000,1650.000000,2.664600,5.780200e+07,1191.000000,1537.000000,4563.000000,4571.162963,0.202453,38021.000000
max,30.000000,0.0,1.0,0.0,100.0,50764.000000,0.073487,48.571000,2700.000000,4.040000,9.581600e+07,5638.000000,3286.000000,20338.000000,20366.408393,0.421168,50421.000000

In [30]:
median_ref_time = df_ref_runs['Time'].median()
print(median_ref_time)
t_median = hr.Time(str(median_ref_time), default_unit=hr.Time.Unit.SECOND)
print(t_median.to_humanreadable())

16901.0
4 hours 41 minutes 41 seconds

In [36]:
mean_ref_time = df_ref_runs['Time'].mean()
print(round(mean_ref_time))

print(get_readable_time(round(mean_ref_time)))

21595
5 hours 59 minutes 55 seconds

In [39]:
min_ref_time = df_ref_runs['Time'].min()
print("min:", get_readable_time(str(min_ref_time)))
max_ref_time = df_ref_runs['Time'].max()
print("max:", get_readable_time(str(max_ref_time)))

min: 30 minutes 49 seconds
max: 14 hours 6 minutes 4 seconds

In [35]:
def get_readable_time(time):
    return hr.Time(str(time), default_unit=hr.Time.Unit.SECOND).to_humanreadable()